version: "3.7"
services:
  torq:
    image: "lncapital/torq:latest"
    restart: always
    depends_on:
      - "db"
    command:
      - --config
      - "<Path>"
      - start
    ports:
      - "<YourPort>:<YourPort>"
  db:
    restart: always
    image: "timescale/timescaledb:latest-pg14"
    environment:
      POSTGRES_PASSWORD: "runningtorq" # Must match db password set above
    volumes:
      - torq_db:/var/lib/postgresql/data
volumes:
  torq_db:
