name: All tests on PR
on:
  pull_request:
    branches:
      - main
jobs:
  run:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/run-all-tests.yml
    secrets: inherit
